# Uncomment the next line to define a global platform for your project



use_frameworks!

target 'LootFox' do

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

# Pods for blackmagk_development

#pod 'EstimoteProximitySDK'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Alamofire'
pod 'GTProgressBar'
end
